version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install

artifacts:
  files:    
    - '**/hello-world-0.0.1-SNAPSHOT.war'
    - 'appspec.yml'
    - 'scripts/application_start'
    - 'scripts/application_stop'
    - 'scripts/install_dependencies'
  discard-paths: yes
